### ISSUE TITLE
method or data member not found. Set json_ParseObject.Item(json_Key)

### ISSUE THREAD

**Issue by sammuelsum** [VBA-tools/VBA-JSON#201]
This is mentioned in one of the issues, but no solution is posted there.  During compilation, the code "Set json_ParseObject.Item(json_Key)" gives an error message "Method or data member not found".

**Comment by sammuelsum** [comment]
Oh Sorry. Did not add the dictionary class.

**Comment by stevenlmas** [comment]
I'm having the same problem.  Did you add the dictionary class from this repo?  Or just add "MS Scripting" in Tools > References.  Or did you have to declare/set something as a dictionary?

**Comment by ericliu0408** [comment]
I still meet the error on the latest release

**Comment by Peter59SE** [comment]
Hi
Running on Win 10 and using O365 this solved the "Method or data member not found" problem in "Function json_ParseObject"

Change Dictionary to Scripting.Dictionary



Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Scripting.Dictionary
    Dim json_Key As String
    Dim json_NextChar As String

    Set json_ParseObject = New Scripting.Dictionary

**Comment by Nick-vanGemeren** [comment]
Peter,

VBA-JSON is written so that the same code can be used on both Mac and Windows. That is why the read.me file says:

- For Windows-only support, include a reference to "Microsoft Scripting Runtime"
- For Mac and Windows support, include [VBA-Dictionary](https://github.com/VBA-tools/VBA-Dictionary)
