### ISSUE TITLE
An expert help me!

### ISSUE THREAD

**Issue by han31ye** [VBA-tools/VBA-JSON#235]
After I converted a VBA code into .exe via Lockxls, I fount the .exe file can't read other excel files. E.g. the VBA code below: 
Debug.print Excel.Application.Workbooks.Count
It = 3 while I debugging with VBA codes, but it =1 while by the .exe file which was converted by the same VBA code？
However, there are at least 3 workbooks at present! Could you please give the kind advise?

**Comment by Nick-vanGemeren** [comment]
You should contact Lockxls for support with a clear explanation of your aims and issue. This should include:
- Versions of Excel and Lockxls
- Which workbooks are using Lockxls and what Lockxls options they are using, especially the access to Excel Object Model and VBA Editor. 
- A precise description of how the workbooks are opened.

Please close your issue here. It has no relevance to VBA-JSON. Other forums (such as Stackoverflow) are available for general Excel or VBA advice.

**Comment by han31ye** [comment]
Dear Sir,

Thanks very much for your advise!

I will take your suggestion and contact Lockxls.

Many thanks!
