### ISSUE TITLE
basic data information

### ISSUE THREAD

**Issue by decoo810** [VBA-tools/VBA-JSON#257]
Hi, I am just check some data from your api, and for "https://date.nager.at/api/v3/PublicHolidays/2022/BG" I've got really suprising information that there : [{"date":"2022-01-03","localName":"Нова година","name":"New Year's Day","countryCode":"BG",". This does not fit to cross checked information. Can you check it?

**Comment by Nick-vanGemeren** [comment]
VBA-JSON is software that lets you process the data returned by the website that you called using other VBA code. It has no knowledge nor responsibility for the data content. You should contact the website manager directly for queries about the data content.

The link which you gave returns a data structure much longer than the fragment you posted. It contains 13 **Public Holidays**. Countries often displace a public holiday which falls at the weekend to the next available weekday. So the Bulgarian public holiday for New Year's Day is displaced from Sat 1 Jan 2022 to Mon 3 Jan 2022. Even more striking is Christmas Day with Sun 25 Dec 2022 displaced to Tue 27 Dec 2022, because Mon 26 Dec 2022 is already a public holiday. But Christmas Eve was not displaced from Sat 24 Dec 2022; nor were the Easter holidays 22-25 Apr 2022.

If the above solves your problem, please close the issue here.

**Comment by decoo810** [comment]
Thank you very much for this explanation. My mistake…
