### ISSUE TITLE
Not work in microsoft word

### ISSUE THREAD

**Issue by yarp-wu** [VBA-tools/VBA-JSON#262]
Issue a error in the code
    Set json_ParseObject = New Dictionary
Not suitable of use the "New" key word.

In this function

Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary
    Dim json_Key As String
    Dim json_NextChar As String

    Set json_ParseObject = New Dictionary

**Comment by Nick-vanGemeren** [comment]
See the discussion in issue #68.
First try (Tools > References) moving the reference to Scripting Runtime above that for the Microsoft Word object library.
If that does not help, edit the code changing the 2`Dictionary`words to `Scripting.Dictionary`.

=============
If this solves your problem, please close your issue here.
