### ISSUE TITLE
Ambiguous "as Dictionary" declaration 

### ISSUE THREAD

**Issue by mr2001** [VBA-tools/VBA-JSON#42]
Please replace any reference to Dictionary by **Scripting.Dictionary**. Reason: if there are references to MSOffice libraries this will be an ambiguous declaration and an error will be returned.

Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Dictionary
change to:
**Private Function json_ParseObject(json_String As String, ByRef json_Index As Long) As Scripting.Dictionary**

Set json_ParseObject = New Dictionary
change to:
**Set json_ParseObject = New Scripting.Dictionary**

**Comment by timhall** [comment]
Hi @mr2001 sorry to hear you're having this issue, but in order to keep Mac support with [VBA-Dictionary](https://github.com/VBA-tools/VBA-Dictionary) the declarations can't be namespaced. I may be able to add a compiler flag in the future, but for now I think your best option is to make your suggested changes in your project.
