### ISSUE TITLE
Vba Runtime Error 14 Out Of String Space

### ISSUE THREAD

**Issue by madmatthemad** [VBA-tools/VBA-JSON#50]
Are there particular limits to the VBA-JSON parser?  In terms of how big a JSON it can parse?   I have been getting Out of String Space errors when running it on one computer when it runs successfully on another.  I appreciate the one it fails on has less memory available to it - but it made me wonder if any empirical testing has been done?  i.e. how big a JSON can be parsed for X amount of memory?  

Or is there anything that can be done to work-around the problem - some setting I can tweak to give me more virtual memory to play with?

**Comment by madmatthemad** [comment]
Oh, the JSON data set I am loading is about 54Mb in size.  If you want to see a copy of it - it is here: [https://mtgjson.com/json/AllCards-x.json.zip](url)

**Comment by CatalinRadoi** [comment]
Damn, I have the exact same error. Did you found the fix?

**Comment by timhall** [comment]
Wow, that's quite the json file. There isn't too much info on the error:

https://msdn.microsoft.com/en-us/library/aa264524(v=vs.60).aspx

Definitely could be running into either of those errors during parsing. Although most likely, I'd imagine if VBA can load the file into memory before passing if the `ParseJson`, it's [this line](https://github.com/VBA-tools/VBA-JSON/blob/b6108e88f956f36397fe82cd805233898e734a73/JsonConverter.bas#L159) that could be causing issues (since there's presumably some temporary strings created there).

I'll look into alternatives to that line (might be able to take it out altogether). Otherwise, might have to look into chunking approaches with the parser, but that'd be a huge change (although very interesting).

**Comment by CatalinRadoi** [comment]
It is not from this line. I have completely commented out this one. I guess that in some parts of the excel the strings are added with + instead of using a StringBuilder like the one from http://www.vbaccelerator.com/home/VB/Code/Techniques/StringBuilder/article.html

**Comment by timhall** [comment]
Hmm, ok I'll use the linked json to do a deeper audit. @CatalinRadoi VBA-JSON already uses most of the StringBuilder concepts internally, for both ConvertToJson and parsing json string values (which was definitely fun / interesting to implement), but l'll check if something slipped through the cracks.

**Comment by madmatthemad** [comment]
I'll try it again tomorrow and report back on the line where it fails.

**Comment by madmatthemad** [comment]
Apologies for the delay - the computer I was using where it failed wasn't available...

OK - running in VBA on a Dell Latitude E6430 with 

This time I've got: 
"Run-time error '430'    Class does not support Automation or does not support expected interface"

Which I wasn't expecting!

I can't then properly "Debug" - as it complains about "Out of Memory" :-/  Sorry!  Was hoping to get a proper debug for you.

**Comment by wgaskill1** [comment]
I'm having the error with the string you identified " JsonString = VBA.Replace(VBA.Replace(VBA.Replace(JsonString, VBA.vbCr, ""), VBA.vbLf, ""), VBA.vbTab, "")".   Have you identified a work-around? I've tried splitting up the string and doing this in pieces, but it still errors with a Jsonstring greater than 50,000,000 lines. (I don't have a capability to decrease the size - it's in a production system).
