### ISSUE TITLE
Kindly help. Getting strange automation error

### ISSUE THREAD

**Issue by parthi2929** [VBA-tools/VBA-JSON#83]
For me, I am getting a strange error which I could not resolve. Below is my code. 

https://gist.github.com/parthi2929/22dfe4463d374ad77ed877c286e48cc1

I am getting error as below there is some automation/unspecified error.  It happens only when I activate the code in problem area (as specified in comments in above link). Strangely previous JSON operation works but when I use 2nd time it is not working and giving this error. 

http://i.cubeupload.com/mRjQt5.png

Kindly help as this is blocking my progress.

**Comment by timhall** [comment]
Hi @parthi2929, sorry you're having this issue, without a little more information I can't pinpoint it exactly, but it looks like you were missing `http.Send` for the second call.

Some debugging tips:

- Move input computation/typing onto separate line to separate underlying issues (e.g. wrong type, invalid http response, etc). I think this would have helped identify your issue.
  ```vb
  Dim Json As String
  Json = Http.ResponseText
  Set Parsed = JsonConverter.ParseJson(Json)
  ```
- Set a breakpoint at the parsing step and use `F8` to step into JsonConverter and keep stepping to hopefully get to the exact line throwing the error so that I can better diagnose

I'm happy to reopen with more information.
